# The key value pairs found below are available within the templates.
# {{site_name}}, {{url}}, {{copyright}} and {{analytics_code}}

:site_name: Bedroll
:url: http://daniel.heath.cc
:copyright: 2012
:analytics_code: ''
